language: ruby
sudo: false
cache: bundler
rvm:
- 2.1.5
bundler_args: "--without kitchen_vagrant"
script:
- bundle exec rubocop
- bundle exec foodcritic --contex --epic-fail any .
- bundle exec kitchen test -c 2 -d always
before_install:
- openssl aes-256-cbc -K $encrypted_137d57b3f9fb_key -iv $encrypted_137d57b3f9fb_iv
  -in .travis/secret_keys.tar.enc -out .travis/secret_keys.tar -d
- tar xf .travis/secret_keys.tar -C .travis
- mv .travis/travis ~/.ssh/id_rsa
deploy:
  edge: true
  provider: chef-supermarket
  user_id: express42
  client_key: ".travis/express42.pem"
  cookbook_category: Programming Languages
  on:
    tags: true
env:
  global:
  - KITCHEN_YAML=.kitchen.cloud.yml
notifications:
  slack:
    secure: OFFf4QFOtCiDr7idO+u6xHVlGOggm3SPg10ppoXU4IDunZRcPimxnZyeZc8SNHQLBAjgxpCYJ+ziuY3CVq/M/KW1fT6ihgcdp0G+7SrKHfhnvWrTeL/F3D2t7XwDJYP2EVmQpXiXfIVVVmALhT4fXxjQ5j+/5LpyP2aJ2NwHOzI=
